modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/lexicon/issues"

[[mods]]
modId="lexicon"
version="1.1.0"
displayName="Lexicon"
itemIcon="minecraft:written_book"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Lexicon.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lexicon"
logoFile="logo.png"
credits="The Minecraft Wiki for some graphics and informations, Translators: pandim"
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds a lexicon to the game that explains almost every aspect of minecraft ingame!
'''

[[dependencies.lexicon]]
    modId="forge"
    mandatory=true
versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lexicon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lexicon]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"